### ISSUE TITLE
I keep getting OOM errors or ResourceExhaustedError: failed to allocate memory [Op:AddV2] whenever I run a verification line for example. Do you have an suggestions of how to fix this? thanks

### ISSUE THREAD

**Issue by Abdelfatah1998** [serengil/deepface#505]
I keep getting OOM errors or ResourceExhaustedError: failed to allocate memory [Op:AddV2] whenever I run a verification line for example. Do you have an suggestions of how to fix this? thanks

**Comment by NguyenTrongThinh** [comment]
Please try this. Add below import deepface

import tensorflow as tf
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    try:
        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
            tf.config.set_logical_device_configuration(gpu, [tf.config.LogicalDeviceConfiguration(memory_limit=4000)])
            logical_gpus = tf.config.list_logical_devices('GPU')
            print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)

**Comment by Abdelfatah1998** [comment]
> 

Thanks a lot for your response. It is working now.

Another way to fix it is by adding the following lines:

import tensorflow as tf
import os
os.environ["CUDA_VISIBLE_DEVICES"]=""
from deepface import DeepFace

# Allow memory growth for the GPU
physical_devices = tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)
